CREATE OR REPLACE PROCEDURE "OLAP".CREATE_BS_OLAP()
	LANGUAGE PLPGSQL AS
$$
DECLARE
BEGIN
	DROP TABLE IF EXISTS "OLAP".DIM_PRODUTO;
	CREATE TABLE "OLAP".DIM_PRODUTO(
		ID_PRODUTO VARCHAR(200),
		CATEGORIA VARCHAR(200),
		PESO FLOAT,
		ALTURA FLOAT,
		COMPRIMENTO FLOAT,
		LARGURA FLOAT);
	
	DROP TABLE IF EXISTS "OLAP".DIM_LOCATION;
	CREATE TABLE "OLAP".DIM_LOCATION(
		CEP VARCHAR(20),
		CIDADE VARCHAR(90),
		UF VARCHAR(90),
		LAT VARCHAR(150),
		LONG VARCHAR(150)
	);

	DROP TABLE IF EXISTS "OLAP".DIM_DATA;
	CREATE TABLE "OLAP".DIM_DATA(
		ID_DATA SERIAL,
		DATA_FULL TIMESTAMP,
		DIA_ANO INT,
		DIA_SEMANA INT,
		DIA_MES INT,
		MES INT,
		SEMANA_ANO INT,
		ANO INT
	);
	
	DROP TABLE IF EXISTS "OLAP".DIM_VENDA;	
	CREATE TABLE "OLAP".DIM_VENDA(
		ID_VENDA VARCHAR(200),
		VALOR_PRODUTO FLOAT,		
		VALOR_FRETE FLOAT,
		VALOR_VENDA FLOAT,
		DATA_COMPRA INT,
		DATA_APROVACAO INT,
		DATA_ENVIO INT,
		DATA_CHEGADA INT,
		DATA_ESTIMADA INT,
		ID_PRODUTO VARCHAR(200),
		CEP_CLIENTE VARCHAR(20),
		CEP_VENDEDOR VARCHAR(20)
	);
	
	
END;$$;