CREATE OR REPLACE PROCEDURE "OLAP".CREATE_DIM_DATA()
	LANGUAGE PLPGSQL AS
$$
DECLARE
	CDATA RECORD;
	CUR_DATA CURSOR FOR
		SELECT DISTINCT XTAB.*
		FROM
			(SELECT DATE_TRUNC('day',PEDIDO.DAT_PEDIDO) AS DATA_FULL,
				   DATE_PART('doy',PEDIDO.DAT_PEDIDO) AS DIA_ANO,
				   DATE_PART('dow',PEDIDO.DAT_PEDIDO) AS DIA_SEMANA,
				   DATE_PART('day',PEDIDO.DAT_PEDIDO) AS DIA_MES,
				   DATE_PART('month',PEDIDO.DAT_PEDIDO) AS MES,
				   DATE_PART('week',PEDIDO.DAT_PEDIDO) AS SEMANA_ANO,
				   DATE_PART('year',PEDIDO.DAT_PEDIDO) AS ANO
			FROM "OLTP".PEDIDO
			UNION ALL
			SELECT DATE_TRUNC('day',PEDIDO.DAT_APROV) AS DATA_FULL,
				   DATE_PART('doy',PEDIDO.DAT_APROV) AS DIA_ANO,
				   DATE_PART('dow',PEDIDO.DAT_APROV) AS DIA_SEMANA,
				   DATE_PART('day',PEDIDO.DAT_APROV) AS DIA_MES,
				   DATE_PART('month',PEDIDO.DAT_APROV) AS MES,
				   DATE_PART('week',PEDIDO.DAT_APROV) AS SEMANA_ANO,
				   DATE_PART('year',PEDIDO.DAT_APROV) AS ANO
			FROM "OLTP".PEDIDO
			UNION ALL
			SELECT DATE_TRUNC('day',PEDIDO.DAT_ENVIO) AS DATA_FULL,
				   DATE_PART('doy',PEDIDO.DAT_ENVIO) AS DIA_ANO,
				   DATE_PART('dow',PEDIDO.DAT_ENVIO) AS DIA_SEMANA,
				   DATE_PART('day',PEDIDO.DAT_ENVIO) AS DIA_MES,
				   DATE_PART('month',PEDIDO.DAT_ENVIO) AS MES,
				   DATE_PART('week',PEDIDO.DAT_ENVIO) AS SEMANA_ANO,
				   DATE_PART('year',PEDIDO.DAT_ENVIO) AS ANO
			FROM "OLTP".PEDIDO
			UNION ALL
			SELECT DATE_TRUNC('day',PEDIDO.DAT_CHEGADA) AS DATA_FULL,
				   DATE_PART('doy',PEDIDO.DAT_CHEGADA) AS DIA_ANO,
				   DATE_PART('dow',PEDIDO.DAT_CHEGADA) AS DIA_SEMANA,
				   DATE_PART('day',PEDIDO.DAT_CHEGADA) AS DIA_MES,
				   DATE_PART('month',PEDIDO.DAT_CHEGADA) AS MES,
				   DATE_PART('week',PEDIDO.DAT_CHEGADA) AS SEMANA_ANO,
				   DATE_PART('year',PEDIDO.DAT_CHEGADA) AS ANO
			FROM "OLTP".PEDIDO
			UNION ALL
			SELECT DATE_TRUNC('day',PEDIDO.DATA_ESTIMADA) AS DATA_FULL,
				   DATE_PART('doy',PEDIDO.DATA_ESTIMADA) AS DIA_ANO,
				   DATE_PART('dow',PEDIDO.DATA_ESTIMADA) AS DIA_SEMANA,
				   DATE_PART('day',PEDIDO.DATA_ESTIMADA) AS DIA_MES,
				   DATE_PART('month',PEDIDO.DATA_ESTIMADA) AS MES,
				   DATE_PART('week',PEDIDO.DATA_ESTIMADA) AS SEMANA_ANO,
				   DATE_PART('year',PEDIDO.DATA_ESTIMADA) AS ANO
			FROM "OLTP".PEDIDO
		)XTAB;
BEGIN
	DELETE FROM "OLAP".DIM_DATA;
	OPEN CUR_DATA;
	LOOP
		FETCH CUR_DATA INTO CDATA;
		EXIT WHEN NOT FOUND;
		
		INSERT INTO "OLAP".DIM_DATA(DATA_FULL,
									DIA_ANO,
									DIA_SEMANA,
									DIA_MES,
									MES,
									SEMANA_ANO,
									ANO)						  						  
					VALUES(CDATA.DATA_FULL,
						   CDATA.DIA_ANO,
						   CDATA.DIA_SEMANA,
						   CDATA.DIA_MES,
						   CDATA.MES,
						   CDATA.SEMANA_ANO,
						   CDATA.ANO);
	END LOOP;
	CLOSE CUR_DATA;
END;$$;