CREATE OR REPLACE PROCEDURE "OLAP".CREATE_DIM_LOCATION()
	LANGUAGE PLPGSQL AS
$$
DECLARE
	CLOCATION RECORD;
	CUR_lOCATION CURSOR FOR
		SELECT GEOLOCATION.CEP AS CEP,
			   MAX(GEOLOCATION.CITY) AS CIDADE,
			   MAX(GEOLOCATION.UF) AS UF,
			   MAX(GEOLOCATION.LAT) AS LAT,
			   MAX(GEOLOCATION.LONG) AS LONG
		FROM "OLTP".GEOLOCATION
		GROUP BY GEOLOCATION.CEP;
BEGIN
	DELETE FROM "OLAP".DIM_LOCATION;
	OPEN CUR_LOCATION;
	LOOP
		FETCH CUR_LOCATION INTO CLOCATION;
		EXIT WHEN NOT FOUND;
		
		INSERT INTO "OLAP".DIM_LOCATION(CEP,
										CIDADE,
										UF,
										LAT,
										LONG)						  						  
					VALUES(CLOCATION.CEP,
						   CLOCATION.CIDADE,
						   CLOCATION.UF,
						   CLOCATION.LAT,
						   CLOCATION.LONG);
	END LOOP;
	CLOSE CUR_LOCATION;
END;$$;