CREATE OR REPLACE PROCEDURE "OLAP".CREATE_DIM_VENDA()
	LANGUAGE PLPGSQL AS
$$
DECLARE
	CVENDA RECORD;
	CUR_VENDA CURSOR FOR
		SELECT	PEDIDO.ID_PEDIDO AS ID_VENDA,
				ITEM_PRODUTO.PRICE AS VALOR_PRODUTO,
				ITEM_PRODUTO.FRETE AS VALOR_FRETE,
				COALESCE(ITEM_PRODUTO.PRICE,0) + COALESCE(ITEM_PRODUTO.FRETE,0) AS VALOR_VENDA,
				DATA_PEDIDO.ID_DATA AS DATA_COMPRA,
				DATA_APROVACAO.ID_DATA AS DATA_APROVACAO,
				DATA_ENVIO.ID_DATA AS DATA_ENVIO,
				DATA_CHEGADA.ID_DATA AS DATA_CHEGADA,
				DATA_ESTIMADA.ID_DATA AS DATA_ESTIMADA,
				ITEM_PRODUTO.ID_PRODUTO,
				CLIENTE.CEP AS CEP_CLIENTE,
				VENDEDOR.CEP AS CEP_VENDEDOR
		FROM "OLTP".PEDIDO 
			LEFT JOIN "OLAP".DIM_DATA AS DATA_APROVACAO ON (DATE_TRUNC('day',PEDIDO.DAT_APROV) = DATA_APROVACAO.DATA_FULL)
			LEFT JOIN "OLAP".DIM_DATA AS DATA_PEDIDO ON (DATE_TRUNC('day',PEDIDO.DAT_PEDIDO)= DATA_PEDIDO.DATA_FULL)
			LEFT JOIN "OLAP".DIM_DATA AS DATA_ENVIO ON (DATE_TRUNC('day',PEDIDO.DAT_ENVIO) = DATA_ENVIO.DATA_FULL)
			LEFT JOIN "OLAP".DIM_DATA AS DATA_CHEGADA ON (DATE_TRUNC('day',PEDIDO.DAT_CHEGADA) = DATA_CHEGADA.DATA_FULL)
			LEFT JOIN "OLAP".DIM_DATA AS DATA_ESTIMADA ON (DATE_TRUNC('day',PEDIDO.DATA_ESTIMADA) = DATA_ESTIMADA.DATA_FULL),
			 "OLTP".ITEM_PRODUTO,
			 "OLTP".CLIENTE,
			 "OLTP".VENDEDOR
		WHERE PEDIDO.ID_PEDIDO = ITEM_PRODUTO.ID_PEDIDO
			  AND ITEM_PRODUTO.ID_VENDEDOR = VENDEDOR.ID_VENDEDOR
			  AND PEDIDO.ID_CLIENTE = CLIENTE.ID_CLIENTE;
			  
BEGIN
	DELETE FROM "OLAP".DIM_VENDA;
	OPEN CUR_VENDA;
	LOOP
		FETCH CUR_VENDA INTO CVENDA;
		EXIT WHEN NOT FOUND;
		
		INSERT INTO "OLAP".DIM_VENDA(ID_VENDA,
						  VALOR_PRODUTO,
						  VALOR_FRETE,
						  VALOR_VENDA,
						  DATA_COMPRA,
						  DATA_APROVACAO,
						  DATA_ENVIO,
						  DATA_CHEGADA,
						  DATA_ESTIMADA,
						  ID_PRODUTO,
						  CEP_CLIENTE,
						  CEP_VENDEDOR)						  						  
					VALUES(CVENDA.ID_VENDA,
						   CVENDA.VALOR_PRODUTO,
						   CVENDA.VALOR_FRETE,
						   CVENDA.VALOR_VENDA,
						   CVENDA.DATA_COMPRA,
						   CVENDA.DATA_APROVACAO,
						   CVENDA.DATA_ENVIO,
						   CVENDA.DATA_CHEGADA,
						   CVENDA.DATA_ESTIMADA,
						   CVENDA.ID_PRODUTO,
						   CVENDA.CEP_CLIENTE,
						   CVENDA.CEP_VENDEDOR);
	END LOOP;
	CLOSE CUR_VENDA;
END;$$;